AWSTemplateFormatVersion: 2010-09-09
Description: poja-sqlite - Storage EFS

Parameters:
  Env:
    Type: String
  FilesystemName:
    Type: String
    Default: poja-sqlite-efs

Resources:
  Filesystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Ref FilesystemName

  FilesystemArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ /poja-sqlite/, !Ref Env, /efs/arn ] ]
      Type: String
      Value: !GetAtt Filesystem.Arn

Outputs:
  FilesystemArnSSM:
    Value: !GetAtt FilesystemArnSSM.Value